### ISSUE TITLE
Cannot find a suitable NPC provider

### ISSUE THREAD

**Issue by nf-projects** [BG-Software-LLC/SSB-IslandNPCs#2]
### Minecraft's Version

1.19.4 paper git-Paper-511

### Plugin's Version

2023.1-b7
IslandNPCs just compiled latest main branch version.

### Describe the bug

The following error occurs on startup when this module is installed:
```


[03:27:17 INFO]: [SuperiorSkyblock2] Enabling the module IslandNPCs...
--
196 | [03:27:17 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while disabling the module IslandNPCs.
197 | [03:27:17 ERROR]: [SuperiorSkyblock2] Contact Ome_R regarding this, this has nothing to do with the plugin.
198 | [03:27:17 WARN]: java.lang.IllegalStateException: Cannot find a suitable NPC provider.
199 | [03:27:17 WARN]: 	at com.bgsoftware.ssbislandnpcs.SSBIslandNPCs.onEnable(SSBIslandNPCs.java:37)
200 | [03:27:17 WARN]: 	at SuperiorSkyblock2-2023.1-b7.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModule(ModulesManagerImpl.java:134)
201 | [03:27:17 WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
202 | [03:27:17 WARN]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
203 | [03:27:17 WARN]: 	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
204 | [03:27:17 WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
205 | [03:27:17 WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
206 | [03:27:17 WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
207 | [03:27:17 WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
208 | [03:27:17 WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
209 | [03:27:17 WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
210 | [03:27:17 WARN]: 	at SuperiorSkyblock2-2023.1-b7.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModules(ModulesManagerImpl.java:173)
211 | [03:27:17 WARN]: 	at SuperiorSkyblock2-2023.1-b7.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:272)
212 | [03:27:17 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279)
213 | [03:27:17 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192)
214 | [03:27:17 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
215 | [03:27:17 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
216 | [03:27:17 WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555)
217 | [03:27:17 WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466)
218 | [03:27:17 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638)
219 | [03:27:17 WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
220 | [03:27:17 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
221 | [03:27:17 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1104)
222 | [03:27:17 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
223 | [03:27:17 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
224 | [03:27:17 INFO]: [SuperiorSkyblock2] Disabling the module IslandNPCs...
225 | [03:27:17 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while disabling the module IslandNPCs.
226 | [03:27:17 ERROR]: [SuperiorSkyblock2] Contact Ome_R regarding this, this has nothing to do with the plugin.
227 | [03:27:17 WARN]: java.lang.NullPointerException: Cannot invoke "com.bgsoftware.ssbislandnpcs.npc.NPCProvider.unloadNPCs()" because "this.npcProvider" is null
228 | [03:27:17 WARN]: 	at com.bgsoftware.ssbislandnpcs.SSBIslandNPCs.onDisable(SSBIslandNPCs.java:54)
229 | [03:27:17 WARN]: 	at SuperiorSkyblock2-2023.1-b7.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.unregisterModule(ModulesManagerImpl.java:92)
230 | [03:27:17 WARN]: 	at SuperiorSkyblock2-2023.1-b7.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModule(ModulesManagerImpl.java:141)
231 | [03:27:17 WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
232 | [03:27:17 WARN]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
233 | [03:27:17 WARN]: 	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
234 | [03:27:17 WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
235 | [03:27:17 WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
236 | [03:27:17 WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
237 | [03:27:17 WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
238 | [03:27:17 WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
239 | [03:27:17 WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
240 | [03:27:17 WARN]: 	at SuperiorSkyblock2-2023.1-b7.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModules(ModulesManagerImpl.java:173)
241 | [03:27:17 WARN]: 	at SuperiorSkyblock2-2023.1-b7.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:272)
242 | [03:27:17 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279)
243 | [03:27:17 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192)
244 | [03:27:17 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
245 | [03:27:17 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
246 | [03:27:17 WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555)
247 | [03:27:17 WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466)
248 | [03:27:17 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638)
249 | [03:27:17 WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
250 | [03:27:17 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
251 | [03:27:17 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1104)
252 | [03:27:17 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
253 | [03:27:17 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

[03:27:17 INFO]: [SuperiorSkyblock2] Enabling the module IslandNPCs...
[03:27:17 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while disabling the module IslandNPCs.
[03:27:17 ERROR]: [SuperiorSkyblock2] Contact Ome_R regarding this, this has nothing to do with the plugin.
[03:27:17 WARN]: java.lang.IllegalStateException: Cannot find a suitable NPC provider.
[03:27:17 WARN]: 	at com.bgsoftware.ssbislandnpcs.SSBIslandNPCs.onEnable(SSBIslandNPCs.java:37)
[03:27:17 WARN]: 	at SuperiorSkyblock2-2023.1-b7.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModule(ModulesManagerImpl.java:134)
[03:27:17 WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[03:27:17 WARN]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[03:27:17 WARN]: 	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
[03:27:17 WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[03:27:17 WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[03:27:17 WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[03:27:17 WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[03:27:17 WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[03:27:17 WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[03:27:17 WARN]: 	at SuperiorSkyblock2-[202](https://mclo.gs/nAN6eJA#L202)3.1-b7.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModules(ModulesManagerImpl.java:173)
[03:27:17 WARN]: 	at SuperiorSkyblock2-2023.1-b7.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:272)
[03:27:17 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279)
[03:27:17 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192)
[03:27:17 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[03:27:17 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[03:27:17 WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555)
[03:27:17 WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466)
[03:27:17 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638)
[03:27:17 WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[03:27:17 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[03:27:17 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1104)
[03:27:17 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[03:27:17 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[03:27:17 INFO]: [SuperiorSkyblock2] Disabling the module IslandNPCs...
[03:27:17 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while disabling the module IslandNPCs.
[03:27:17 ERROR]: [SuperiorSkyblock2] Contact Ome_R regarding this, this has nothing to do with the plugin.
[03:27:17 WARN]: java.lang.NullPointerException: Cannot invoke "com.bgsoftware.ssbislandnpcs.npc.NPCProvider.unloadNPCs()" because "this.npcProvider" is null
[03:27:17 WARN]: 	at com.bgsoftware.ssbislandnpcs.SSBIslandNPCs.onDisable(SSBIslandNPCs.java:54)
[03:27:17 WARN]: 	at SuperiorSkyblock2-2023.1-b7.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.unregisterModule(ModulesManagerImpl.java:92)
[03:27:17 WARN]: 	at SuperiorSkyblock2-2023.1-b7.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModule(ModulesManagerImpl.java:141)
[03:27:17 WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[03:27:17 WARN]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[03:27:17 WARN]: 	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
[03:27:17 WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[03:27:17 WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[03:27:17 WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[03:27:17 WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[03:27:17 WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[03:27:17 WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[03:27:17 WARN]: 	at SuperiorSkyblock2-2023.1-b7.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModules(ModulesManagerImpl.java:173)
[03:27:17 WARN]: 	at SuperiorSkyblock2-2023.1-b7.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:272)
[03:27:17 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279)
[03:27:17 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192)
[03:27:17 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[03:27:17 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[03:27:17 WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555)
[03:27:17 WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466)
[03:27:17 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638)
[03:27:17 WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[03:27:17 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[03:27:17 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1104)
[03:27:17 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[03:27:17 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

### To Reproduce

- Install the module on the given plugin/server versions
- Install latest citizens build
- Start server

**Comment by OmerBenGera** [comment]
Make sure you install Citizens.

**Comment by nf-projects** [comment]
@OmerBenGera

**Comment by OmerBenGera** [comment]
This module is not supported at this moment.
